---
- name: Install the repository RPM
  dnf:
    name: 'https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm'
    state: present
    disable_gpg_check: yes

- name: Disable the built-in PostgreSQL module
  shell: 'dnf -qy module disable postgresql'
 

- name: Install PostgreSQL
  yum:
    name: postgresql14-server
    state: present


- name: Optionally initialize the database
  shell: /usr/pgsql-14/bin/postgresql-14-setup initdb
  ignore_errors: true

- name: Enable and start postgres14
  systemd:
    name: postgresql-14
    state: started
    enabled: yes
