---
- name: Enable and start postgres14
  systemd:
    name: postgresql-14
    state: stopped
    enabled: yes

- name: Backup data folder
  copy: 
    src: /var/lib/pgsql/14/data
    dest: /var/lib/pgsql/14/data_orig
    remote_src: true


- name: Delete content & directory
  file:
    path: /var/lib/pgsql/14/data/
    state: absent


- name: Run pg_basebackup
  become_user: postgres
  shell: "PGPASSWORD=replicator pg_basebackup -h 192.168.255.1 -D /var/lib/pgsql/14/data -U replicator -P -v  -R -X stream -C -S pgstandby1"
  ignore_errors: true


- name: Enable and start postgres14
  systemd:
    name: postgresql-14
    state: started
    enabled: yes
  ignore_errors: true
