---
- name: Install the repository RPM
  dnf:
    name: 'https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm'
    state: present
    disable_gpg_check: yes

- name: Disable the built-in PostgreSQL module
  shell: 'dnf -qy module disable postgresql'
 

- name: Install PostgreSQL
  dnf:
    name: postgresql14
    state: present

- name: Install barman
  yum:
    name: barman
    state: present

- name: Copy ssh files
  copy: 
    src: '{{item.file}}'
    dest: /var/lib/barman/.ssh/  
    owner: barman
    group: barman
    mode: '{{item.mode}}'
  loop: 
    - { file: id_rsa, mode: '0600' }
    - { file: id_rsa.pub, mode: '0644' }
    - { file: authorized_keys, mode: '0600' }


- name: Copy barman config
  copy:
    src: barman.conf
    dest: /etc/barman.conf


- name: Copy barman backup server config
  template:
    src: backup.conf.j2
    dest: /etc/barman.d/master.conf
    mode: '0644'


- name: Force Switch WAL in Barman Server
  become_user: barman
  shell: barman receive-wal --create-slot master


# nohup barman receive-wal master


- name: Force Switch WAL in Barman Server
  become_user: barman
  shell: barman switch-wal --force --archive master
